export const reviews = [
  {
    id: 1,
    name: "Dbasenet",
    stars: 5,
    text: "“La automatización con FacturaGPT nos ha ahorrado semanas de trabajo al año. Antes, nuestro equipo pasaba horas manualmente revisando facturas. Ahora, todo es rápido, preciso y eficiente. Sin duda, la mejor herramienta del mercado”",
  },
  {
    id: 2,
    name: "WinPaying Solutions",
    stars: 5,
    text: "“Usar FacturaGPT fue la mejor decisión para nuestra empresa. Hemos reducido el tiempo de respuesta en la gestión de pagos y cobros drásticamente. Una herramienta imprescindible.”",
  },
  {
    id: 3,
    name: "DigitalWave",
    stars: 5,
    text: "“FacturaGPT nos ha facilitado la generación y el envío de facturas de manera automática. Antes dedicábamos horas a crear documentos y enviarlos manualmente, pero ahora todo se hace en segundos. ¡Hemos optimizado nuestro proceso de facturación al máximo!",
  },
  {
    id: 4,
    name: "StartUpPlus",
    stars: 5,
    text: "“FacturaGPT nos ha facilitado la generación y el envío de facturas de manera automática. Antes dedicábamos horas a crear documentos y enviarlos manualmente, pero ahora todo se hace en segundos. ¡Hemos optimizado nuestro proceso de facturación al máximo!",
  },
  {
    id: 5,
    name: "Dbasenet",
    stars: 5,
    text: "“La automatización con FacturaGPT nos ha ahorrado semanas de trabajo al año. Antes, nuestro equipo pasaba horas manualmente revisando facturas. Ahora, todo es rápido, preciso y eficiente. Sin duda, la mejor herramienta del mercado”",
  },
  {
    id: 6,
    name: "WinPaying Solutions",
    stars: 5,
    text: "“Usar FacturaGPT fue la mejor decisión para nuestra empresa. Hemos reducido el tiempo de respuesta en la gestión de pagos y cobros drásticamente. Una herramienta imprescindible.”",
  },
  {
    id: 7,
    name: "DigitalWave",
    stars: 5,
    text: "“FacturaGPT nos ha facilitado la generación y el envío de facturas de manera automática. Antes dedicábamos horas a crear documentos y enviarlos manualmente, pero ahora todo se hace en segundos. ¡Hemos optimizado nuestro proceso de facturación al máximo!",
  },
  {
    id: 8,
    name: "StartUpPlus",
    stars: 5,
    text: "“FacturaGPT nos ha facilitado la generación y el envío de facturas de manera automática. Antes dedicábamos horas a crear documentos y enviarlos manualmente, pero ahora todo se hace en segundos. ¡Hemos optimizado nuestro proceso de facturación al máximo!",
  },
  {
    id: 9,
    name: "Dbasenet",
    stars: 5,
    text: "“La automatización con FacturaGPT nos ha ahorrado semanas de trabajo al año. Antes, nuestro equipo pasaba horas manualmente revisando facturas. Ahora, todo es rápido, preciso y eficiente. Sin duda, la mejor herramienta del mercado”",
  },
  {
    id: 10,
    name: "WinPaying Solutions",
    stars: 5,
    text: "“Usar FacturaGPT fue la mejor decisión para nuestra empresa. Hemos reducido el tiempo de respuesta en la gestión de pagos y cobros drásticamente. Una herramienta imprescindible.”",
  },
  {
    id: 11,
    name: "DigitalWave",
    stars: 5,
    text: "“FacturaGPT nos ha facilitado la generación y el envío de facturas de manera automática. Antes dedicábamos horas a crear documentos y enviarlos manualmente, pero ahora todo se hace en segundos. ¡Hemos optimizado nuestro proceso de facturación al máximo!",
  },
  {
    id: 12,
    name: "StartUpPlus",
    stars: 5,
    text: "“FacturaGPT nos ha facilitado la generación y el envío de facturas de manera automática. Antes dedicábamos horas a crear documentos y enviarlos manualmente, pero ahora todo se hace en segundos. ¡Hemos optimizado nuestro proceso de facturación al máximo!",
  },
  {
    id: 13,
    name: "Dbasenet",
    stars: 5,
    text: "“La automatización con FacturaGPT nos ha ahorrado semanas de trabajo al año. Antes, nuestro equipo pasaba horas manualmente revisando facturas. Ahora, todo es rápido, preciso y eficiente. Sin duda, la mejor herramienta del mercado”",
  },
  {
    id: 14,
    name: "WinPaying Solutions",
    stars: 5,
    text: "“Usar FacturaGPT fue la mejor decisión para nuestra empresa. Hemos reducido el tiempo de respuesta en la gestión de pagos y cobros drásticamente. Una herramienta imprescindible.”",
  },
  {
    id: 15,
    name: "DigitalWave",
    stars: 5,
    text: "“FacturaGPT nos ha facilitado la generación y el envío de facturas de manera automática. Antes dedicábamos horas a crear documentos y enviarlos manualmente, pero ahora todo se hace en segundos. ¡Hemos optimizado nuestro proceso de facturación al máximo!",
  },
  {
    id: 16,
    name: "StartUpPlus",
    stars: 5,
    text: "“FacturaGPT nos ha facilitado la generación y el envío de facturas de manera automática. Antes dedicábamos horas a crear documentos y enviarlos manualmente, pero ahora todo se hace en segundos. ¡Hemos optimizado nuestro proceso de facturación al máximo!",
  },
];
