export const benefits = [
  {
    name: "Documentos",
    basic: "Hasta 20 al mes",
    standard: "20 - 2.000 al mes",
    pro: "2.000 - 20.000 al mes",
    enterprise: "20.000 - 100.000 al mes",
  },
  {
    name: "Creación de contactos",
    basic: "Hasta 50 contactos",
    standard: "Ilimitado",
    pro: "Ilimitado",
    enterprise: "Ilimitado",
  },
  {
    name: "Gestión de activos",
    basic: "Hasta 100 activos",
    standard: "Ilimitado",
    pro: "Ilimitado",
    enterprise: "Ilimitado",
  },
  {
    name: "Respuestas de chat",
    basic: "Hasta 10 al día",
    standard: "Hasta 100 al día",
    pro: "Hasta 1000 al día",
    enterprise: "Ilimitado",
  },
  {
    name: "Divisas",
    basic: "EUR y USD",
    standard: "Todas",
    pro: "Todas",
    enterprise: "Todas",
  },
  {
    name: "Acceso y custodia de facturas",
    basic: "3 meses",
    standard: "Período legal",
    pro: "Período legal",
    enterprise: "Período legal",
  },
  {
    name: "Copias de seguridad diarias",
    basic: "not include",
    standard: "include",
    pro: "include",
    enterprise: "include",
  },
  {
    name: "Almacenamiento de documentos ilimitado",
    basic: "not include",
    standard: "include",
    pro: "include",
    enterprise: "include",
  },
  {
    name: "Acceso en tiempo real a documentos desde cualquier dispositivo",
    basic: "include",
    standard: "include",
    pro: "include",
    enterprise: "include",
  },
  {
    name: "Búsqueda avanzada de documentos con filtros avanzados",
    basic: "include",
    standard: "include",
    pro: "include",
    enterprise: "include",
  },
  {
    name: "Conversión directa de presupuesto a factura sin duplicar datos",
    basic: "include",
    standard: "include",
    pro: "include",
    enterprise: "include",
  },
  {
    name: "Integración con banca online para conciliación automática",
    basic: "not include",
    standard: "include",
    pro: "include",
    enterprise: "include",
  },
  {
    name: "Firma de facturas PDF",
    basic: "include",
    standard: "include",
    pro: "include",
    enterprise: "include",
  },
  {
    name: "QR identificativo",
    basic: "include",
    standard: "include",
    pro: "include",
    enterprise: "include",
  },
  {
    name: "Control de estados de facturas con alertas de vencimiento (Pendiente, Incumplido, Vencido, Pagado, Anulado)",
    basic: "include",
    standard: "include",
    pro: "include",
    enterprise: "include",
  },
  {
    name: "Envío ilimitado de facturas nacionales e internacionales",
    basic: "include",
    standard: "include",
    pro: "include",
    enterprise: "include",
  },
  {
    name: "Importación de facturas en más de 10 formatos",
    basic: "include",
    standard: "include",
    pro: "include",
    enterprise: "include",
  },
  {
    name: "Exportación de datos en Excel, CSV, XML, PDF",
    basic: "include",
    standard: "include",
    pro: "include",
    enterprise: "include",
  },
  {
    name: "Impresión y envío de facturas por email en PDF y XML",
    basic: "include",
    standard: "include",
    pro: "include",
    enterprise: "include",
  },
  {
    name: "Adjuntos en cada factura: órdenes de compra, contratos, etc.",
    basic: "include",
    standard: "include",
    pro: "include",
    enterprise: "include",
  },
  {
    name: "Generación de recibos y remesas bancarias en formato SEPA",
    basic: "not include",
    standard: "include",
    pro: "include",
    enterprise: "include",
  },
  {
    name: "Registro de ingresos y costes",
    basic: "include",
    standard: "include",
    pro: "include",
    enterprise: "include",
  },
  {
    name: "Gestión de diferentes tasas de IVA",
    basic: "include",
    standard: "include",
    pro: "include",
    enterprise: "include",
  },
  {
    name: "Envío automático de facturas al portal de la Agencia Tributaria",
    basic: "include",
    standard: "include",
    pro: "include",
    enterprise: "include",
  },
  {
    name: "Gestión de Descuentos",
    basic: "include",
    standard: "include",
    pro: "include",
    enterprise: "include",
  },
  {
    name: "Carga masiva de clientes y activos desde Excel",
    basic: "include",
    standard: "include",
    pro: "include",
    enterprise: "include",
  },
  {
    name: "Múltiples direcciones de facturación y entrega por cliente",
    basic: "include",
    standard: "include",
    pro: "include",
    enterprise: "include",
  },
  {
    name: "Alertas y notificaciones",
    basic: "include",
    standard: "include",
    pro: "include",
    enterprise: "include",
  },
  {
    name: "Análisis comparativo",
    basic: "include",
    standard: "include",
    pro: "include",
    enterprise: "include",
  },
  {
    name: "Análisis de flujo de caja y previsión de ingresos",
    basic: "include",
    standard: "include",
    pro: "include",
    enterprise: "include",
  },
  {
    name: "Gráficos de evolución de facturación por activo y clientes",
    basic: "include",
    standard: "include",
    pro: "include",
    enterprise: "include",
  },
  {
    name: "Gestión de almacenes",
    basic: "not include",
    standard: "include",
    pro: "include",
    enterprise: "include",
  },
];
