export const plansData = [
  {
    title: "Freemium",
    price: "0.00",
    priceTag: "FREE",
    documentPrices: [],
    features: [
      "Hasta 20 documentos por cuenta",
      "Invita a miembros del equipo",
      "E-mail support",
      "Google Gmail",
      "Microsoft Outlook",
    ],
  },
  {
    title: "Plus",
    price: "-",
    documentPrices: [
      "0.20€ for document",
      "0.19€ for document",
      "0.18€ for document",
      "0.16€ for document",
    ],
    features: [
      "20-2.000 documentos",
      "Información de los perfiles de empresas",
      "Almacenamiento ilimitado de documentos",
      "Priority support",
      "Google Gmail",
      "Microsoft Outlook",
    ],
  },
  {
    title: "Pro",
    price: "-",
    documentPrices: ["0.15€ for document", "0.13€ for document"],
    features: [
      "20-2.000 documentos",
      "Información de los perfiles de empresas",
      "Almacenamiento ilimitado de documentos",
      "Priority support",
      "Google Gmail",
      "Microsoft Outlook",
      "Acceso a la comunidad",
    ],
  },
  {
    title: "Enterprise",
    price: "-",
    documentPrices: [
      "0.11€ for document",
      "0.09€ for document",
      "0.05€ for document",
    ],
    features: [
      "20.000-100.000 documentos",
      "Información de los perfiles de empresas",
      "Almacenamiento ilimitado de documentos",
      "Priority support",
      "Google Gmail",
      "Microsoft Outlook",
      "Acceso a la comunidad",
    ],
  },
  {
    title: "¿Aún más?",
    price: "-",
    priceTag: "Talk with sales",
    documentPrices: [],
    features: [
      "Información de los perfiles de empresas",
      "Almacenamiento ilimitado de documentos",
      "Priority support",
      "¿No encuentras tu sistema de facturación? ¡Contáctenos!",
      "Acceso a la comunidad",
    ],
  },
];
