export const plansData = [
  {
    title: "Freemium",
    price: "0.00",
    priceTag: "FREE",
    documentPrices: [],
    features: [
      "Hasta 20 documentos por cuenta",
      "Información básica de los perfiles de empresas",
      "50 company or officer profiles",
      "E-mail support",
      "Almacenamiento ilimitado de documentos",
      "Basic Business Information",
      "Google Integration",
    ],
  },
  {
    title: "Basic",
    price: "-",
    documentPrices: [
      "0.20€ for document",
      "0.19€ for document",
      "0.18€ for document",
      "0.16€ for document",
    ],
    features: [
      "20+",
      "Información básica de los perfiles de empresas",
      "50 company or officer profiles",
      "E-mail support",
      "Almacenamiento ilimitado de documentos",
      "Basic Business Information",
      "Google Integration",
    ],
  },
  {
    title: "Pro",
    price: "-",
    documentPrices: ["0.15€ for document", "0.13€ for document"],
    features: [
      "Información básica de los perfiles de empresas",
      "50 company or officer profiles",
      "E-mail support",
      "Almacenamiento ilimitado de documentos",
      "Basic Business Information",
      "Google Integration",
    ],
  },
  {
    title: "Enterprise",
    price: "-",
    documentPrices: [
      "0.11€ for document",
      "0.09€ for document",
      "0.05€ for document",
    ],
    features: [
      "Información básica de los perfiles de empresas",
      "50 company or officer profiles",
      "E-mail support",
      "Almacenamiento ilimitado de documentos",
      "Basic Business Information",
      "Google Integration",
    ],
  },
  {
    title: "¿Aún más?",
    price: "-",
    priceTag: "Talk with sales",
    documentPrices: [],
    features: [
      "Información básica de los perfiles de empresas",
      "50 company or officer profiles",
      "E-mail support",
      "Almacenamiento ilimitado de documentos",
      "Basic Business Information",
      "Google Integration",
    ],
  },
];
